version = 1

; Shared defaults for each worker (override per-model below if needed).
[*]
c = 8192

[unsloth/GLM-4.7-Flash-GGUF:Q6_K]
hf-repo = unsloth/GLM-4.7-Flash-GGUF:Q6_K

[unsloth/Qwen3-32B-GGUF:Q4_K_M]
hf-repo = unsloth/Qwen3-32B-GGUF:Q4_K_M
